# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghc-7.10.3

# Local packages, usually specified by relative directory name
packages:
- '.'
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- HTTP-4000.3.1
- HUnit-1.3.1.0
- JuicyPixels-3.2.6.4
- MonadCatchIO-transformers-0.3.1.3
- SHA-1.6.4.2
- StateVar-1.1.0.2
- aeson-0.10.0.0
- aeson-pretty-0.7.2
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.13.0.1
- attoparsec-enumerator-0.3.4
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- blaze-builder-enumerator-0.2.1.0
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- bytestring-builder-0.10.6.0.0
- bytestring-mmap-0.2.2
- case-insensitive-1.2.0.5
- cereal-0.5.1.0
- cmark-0.5.0
- cmdargs-0.10.13
- conduit-1.2.6.1
- conduit-extra-1.1.9.2
- connection-0.2.5
- contravariant-1.3.3
- cookie-0.4.1.6
- cryptohash-0.11.6
- cryptonite-0.10
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.1.1.2
- digest-0.0.1.2
- dlist-0.7.1.2
- enclosed-exceptions-1.0.1.1
- enumerator-0.4.20
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- filemanip-0.3.6.3
- fsnotify-0.2.1
- haddock-library-1.2.1
- hakyll-4.7.5.1
- hashable-1.2.3.3
- highlighting-kate-0.6.1
- hinotify-0.3.8.1
- hourglass-0.2.9
- hs-bibutils-5.5
- hslua-0.4.1
- http-client-0.4.26.2
- http-client-tls-0.2.2
- http-conduit-2.1.8
- http-types-0.9
- lifted-base-0.2.3.6
- lrucache-1.2.0.0
- memory-0.11
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- monads-tf-0.1.0.2
- mtl-2.2.1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- pandoc-1.16.0.1
- pandoc-citeproc-0.9
- pandoc-types-1.16.0.1
- parsec-3.1.9
- pem-0.2.2
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-pcre-builtin-0.94.4.8.8.35
- regex-posix-0.95.2
- regex-tdfa-1.2.1
- resourcet-1.1.7
- rfc5051-0.1.0.3
- scientific-0.3.4.4
- semigroups-0.18.0.1
- setenv-0.1.1.3
- snap-core-0.9.8.0
- snap-server-0.9.5.1
- socks-0.5.4
- split-0.2.3
- stm-2.4.4.1
- streaming-commons-0.1.15
- syb-0.6
- system-filepath-0.4.13.4
- tagged-0.8.2
- tagsoup-0.13.8
- temporary-1.2.0.3
- texmath-0.8.4.1
- text-1.2.2.0
- time-locale-compat-0.1.1.1
- tls-1.3.4
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- xml-1.3.14
- xml-conduit-1.3.3
- xml-types-0.3.6
- yaml-0.8.15.2
- zip-archive-0.2.3.7
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1

# Override default flag values for local packages and extra-deps
flags:
  time-locale-compat:
    old-locale: false
    
# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
system-ghc: false

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]